name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Build Maven Env for Autogen
        run: ./mvnw clean install -T1C

      - name: Build with Maven on Jacoco-exec
        run: ./mvnw --show-version --batch-mode --no-transfer-progress verify -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -Dsurefire.failIfNoSpecifiedTests=false

      - name: Merge coverage report
        run: ./.github/workflows/resources/scripts/unit-test-coverage-merge/code-coverage-merge.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      #uses: codecov/codecov-action@v4
        with:
          files: ./.github/workflows/resources/scripts/unit-test-coverage-merge/mergeReport/jacoco.xml