name: Coverage

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 8 ]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn --show-version --batch-mode --no-transfer-progress verify -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -Dsurefire.failIfNoSpecifiedTests=false

      - name: Merge coverage report
        run: ./.github/workflows/resources/scripts/unit-test-coverage-merge/code-coverage-merge.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      #uses: codecov/codecov-action@v4
        with:
          files: ./.github/workflows/resources/scripts/unit-test-coverage-merge/mergeReport/jacoco.xml